### ISSUE TITLE
Rename SML::Raw to SML::Fragment (RAW -> FRAGMENT)

### ISSUE THREAD

**Issue by drj826** [drj826/SML#35]
What I am currently calling "RAW" divisions are really re-usable fragments.  I think it would make more sense to call them "FRAGMENT" divisions instead of "RAW" divisions.  The reason I didn't call them "FRAGMENT" divisions in the first place is that at the time I implemented SML::Raw there was another class called SML::Fragment which has since been deprecated.

**Comment by dgpicke** [comment]
Fragment might also be considered 'fragmented' or 'fragmentation'.  Raw divisions might not be fragmented.  How about 'reusable fragments or classes' - calling them 'inherited'.  or - maybe not.

**Comment by drj826** [comment]
The intended meaning is "reusable document fragment."  In practical application the chosen term will be used as a division name:

> >>>FRAGMENT.my-fragment
>
> This is a document fragment that can be reused in
> any number of documents by using the 'include' element.
>
> <<<FRAGMENT
