### ISSUE TITLE
Implement Header and Footer Capability

### ISSUE THREAD

**Issue by drj826** [drj826/SML#37]
The ontology makes provisions for header and footer information.  However, it points to non-existent SML::Header and SML::Footer classes in the object model and there are also no templates for headers and footers.

The legacy code has header and footer capability.

**Comment by dgpicke** [comment]
non-existent code segments in classes, sounds like a Microsoft methodology.

**Comment by drj826** [comment]
The ontology is a "configuration file" and not a class.  A better way to understand this is that a configuration file is pointing to a non-existent class.  It doesn't cause a problem right now because none of the SML Engineering Library documents have headers or footers.

**Comment by drj826** [comment]
How does the template system know whether the document contains a header or footer?

> [%- IF document.contains_header -%]
> insert CSS or HTML header text here...
> [%- END -%]
>
> [%- IF document.contains_footer -%]
> insert CSS or HTML footer text here...
> [%- END -%]


That's how

**Comment by dgpicke** [comment]
nice !! 

----- Original Message -----

**Comment by drj826** [comment]
The SML code uses the Perl Template Toolkit for rendering output.  (http://template-toolkit.org/)  You can learn everything you need to know about the toolkit in about an hour.  Template files reside in SML/library/templates/<rendition>/<style>.  Check out SML/library/templates/html/default for a good does of how this works.
